# Site settings
title: AndersWik
email: about@anderswiik.se
description: > # this means to ignore newlines until "baseurl:"
  Awesome description for this site here! Yes it is Jekyll (jekyllrb.com)..
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://anderswiik.se" # the base hostname & protocol for your site
twitter_username: AndersWik_
github_username:  AndersWik

paginate: 10
# Build settings
markdown: kramdown
