# Site settings
title: AndersWik
email: about@anderswiik.se
description: > # this means to ignore newlines until "baseurl:"
  Awesome description for this site here! When browsing the web i stumbled on Jekyll (jekyllrb.com) and I guess I have a blog now..
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://anderswiik.se" # the base hostname & protocol for your site
twitter_username: AndersWik_
github_username:  AndersWik

# Build settings
markdown: kramdown
