# Site settings
title: AndersWik
email: ""
description: > # this means to ignore newlines until "baseurl:"
  This is some notes about stuff.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://anderswik.se" # the base hostname & protocol for your site
twitter_username: AndersWik_
github_username:  AndersWik
linkedin_username: anders-wik-80208aa2

plugins: []
paginate: 10
paginate_path: "page:num"

# Build settings
markdown: kramdown
